# Generated by Django 5.1.3 on 2024-12-10 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('vehicle_sign', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.CharField(default='ACS', max_length=20, unique=True)),
                ('chasis_no', models.CharField(default='DEFAULT-CHASIS-NO', max_length=20, unique=True)),
                ('vehicle_type', models.CharField(default='CAMPUS-SHUTTLE', max_length=20)),
                ('vehicle_sign', models.CharField(default='DEFAULT-VEHICLE-SIGNATURE', max_length=50, unique=True)),
                ('mfg_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='user_dashboard.client')),
            ],
        ),
    ]
